= info-gzip

== What?
While helping out with https://github.com/babashka/fs[babashka/fs], I became curious about what can be in a gzip file.
This little repo describes my explorations.

== References
- https://www.ietf.org/rfc/rfc1952.txt[rfc1952] describes the gzip file format. It is well written and there's not much to it.
- https://en.wikipedia.org/wiki/Mark_Adler[Mark Adler], one of the authors of gzip, is active and helpful on https://stackoverflow.com/users/1180620/mark-adler[stackoverlow].

== Of Note
Read the spec for full details, these are just some things I found interesting.

=== ISO-8859-1 encoding
The spec says `original file name` and `file comment` fields are to be encoded in ISO-8859-1.
I wonder if in these UNICODE days, folks adhere to this.

=== original file name field
The optional `original file name` field stores the original name of the gzipped file.
It is populated on compress but ignored by default by `gzip` command on decompress.

[source,shell]
----
$ echo foo > foo.txt
$ gzip foo.txt
$ mv foo.txt.gz bar.txt.gz
$ gzip --decompress --keep bar.txt.gz
$ ls
bar.txt  bar.txt.gz
----

Restoring the `original file name` can be forced via `--name`.

[source,shell]
----
$ rm bar.txt
$ gzip --decompress --keep --name bar.txt.gz
$ ls
bar.txt.gz  foo.txt
----
=== file comment field
As far as I can tell, the `file comment` field goes unused by the `gzip` command.

=== extra field
The spec defines a way to specify an `extra field` with subfields.
These, as far as I can tell, are not used by the `gzip` command.

=== crc16 header field
The `gzip` command does not generate this field.
There is a `crc32` trailer field that is populated though.

=== os field
The `os` field seems to more describe the file system.

=== compressed blocks
The is no indication of the size of compressed blocks.
As far as I could muster, decompression is necessary to determine the size of the compressed blocks.

NOTE: The trailer has a fixed length of 8 bytes.
But we cannot assume only 1 link:#member[member] in a gzip file.

=== Java API
Java includes support for compressing and decompressing gzip files.
The API works at the stream level.
I does not populate or give access to any of the optional gzip fields including `original file name`.
It populates the `os` field with `255` which means `unkown`.

[[member]]
=== Multiple Members
A gzip file can contain multiple members.
Each member can, syntactically, be thought of as a complete gzip file.

[source,shell]
----
$ echo foo > foo.txt
$ echo bar > bar.txt
$ gzip --stdout foo.txt  > foo.gz
$ gzip --stdout bar.txt >> foo.gz
----

Members are concatenated when decompressed:
[source,shell]
----
$ rm foo.txt bar.txt
$ gzip --decompress --keep foo.gz
$ cat foo
foo
bar
----

And if we try to preserve the `original file name`? Seems like the `gzip` command uses the first member:
[source,shell]
----
$ rm foo
$ gzip --decompress --keep --name foo.gz
$ ls
foo.gz foo.txt
$ cat foo.txt
foo
bar
----

I assume storing multiple members in a single gzip file is rare.

== Explorations

=== What's in a gzip file?
I whipped up a wee Clojure app link:gzip_info.clj[gzip_info.clj] to explore what is in a gzip file.

Example usage (run via https://github.com/babashka/babashka#installation[babashka]):
[source,shell]
----
$ echo foo > foo.txt
$ gzip foo.txt
$ bb gzip_info.clj foo.txt.gz

----
Example output:
[source,clojure]
----
[{:crc32 2117232040,
  :flags
  {:ftext false,
   :fhcrc false,
   :fextra false,
   :fname true,
   :fcomment false},
  :isize 4,
  :mtime "2026-01-06T22:28:13Z",
  :original-file-name "foo.txt",
  :os :unix,
  :raw-fixed-header
  {:id1 31, :id2 139, :cm 8, :flg 8, :mtime 1767738493, :xfl 0, :os 3},
  :uncompressed-string "foo\n",
  :xfl :default}]
----

=== A gzip File With Fields Populated
Mark Adler https://stackoverflow.com/a/79515997[shared a nice little C program] to generate a gzip file with "the works".

I saved a copy under link:/gz_the_works.c[gz_the_works.c].

On Linux, I compiled and ran like so:
[source, shell]
----
$ gcc -o gz_the_works gz_the_works.c -lz
$ ./gz_the_works > the_works.gz
----

And we can take a peek like so:
[source,clojure]
----
$ bb gzip_info.clj the_works.gz
[{:crc16 2541,
  :crc32 392113465,
  :extra-field [{:s1 120, :s2 49, :subfield "abcd"}],
  :file-comment "no comment",
  :flags
  {:ftext true,
   :fhcrc true,
   :fextra true,
   :fname true,
   :fcomment true},
  :isize 81,
  :mtime "2026-01-06T22:30:04Z",
  :original-file-name "foo.bar",
  :os :unix,
  :raw-fixed-header
  {:id1 31,
   :id2 139,
   :cm 8,
   :flg 31,
   :mtime 1767738604,
   :xfl 0,
   :os 3},
  :uncompressed-string
  "This is a test of the emergency broadcast system.\nRemember, this is only a test.\n",
  :xfl :default}]
----

=== A gzip File Generated by the Java API

Easy to do with babashka:
[source, shell]
----
$ echo jvm > jvm.txt
$ bb --eval '(fs/gzip "jvm.txt")'
----

Let's take a peek:
[source,clojure]
----
$ bb gzip_info.clj jvm.txt.gz
[{:crc32 354754669,
  :flags
  {:ftext false,
   :fhcrc false,
   :fextra false,
   :fname false,
   :fcomment false},
  :isize 4,
  :os :unknown,
  :raw-fixed-header
  {:id1 31, :id2 139, :cm 8, :flg 0, :mtime 0, :xfl 0, :os 255},
  :uncompressed-string "jvm\n",
  :xfl :default}]
----

=== A Multi-Member gzip File
Assuming you have not deleted the gz files from explorations above:

[source,shell]
----
$ cat foo.txt.gz the_works.gz jvm.txt.gz > multi.gz
----

A little sanity test with `gzip` command:
[source,shell]
----
$ gzip --decompress --stdout multi.gz
foo
This is a test of the emergency broadcast system.
Remember, this is only a test.
jvm
----

And a peek with gzip_info (newlines added by me for readability):
[source,clojure]
----
$ bb gzip_info.clj multi.gz
[{:crc32 2117232040,
  :flags
  {:ftext false,
   :fhcrc false,
   :fextra false,
   :fname true,
   :fcomment false},
  :isize 4,
  :mtime "2026-01-06T22:28:13Z",
  :original-file-name "foo.txt",
  :os :unix,
  :raw-fixed-header
  {:id1 31, :id2 139, :cm 8, :flg 8, :mtime 1767738493, :xfl 0, :os 3},
  :uncompressed-string "foo\n",
  :xfl :default}

 {:crc16 2541,
  :crc32 392113465,
  :extra-field [{:s1 120, :s2 49, :subfield "abcd"}],
  :file-comment "no comment",
  :flags
  {:ftext true,
   :fhcrc true,
   :fextra true,
   :fname true,
   :fcomment true},
  :isize 81,
  :mtime "2026-01-06T22:30:04Z",
  :original-file-name "foo.bar",
  :os :unix,
  :raw-fixed-header
  {:id1 31,
   :id2 139,
   :cm 8,
   :flg 31,
   :mtime 1767738604,
   :xfl 0,
   :os 3},
  :uncompressed-string
  "This is a test of the emergency broadcast system.\nRemember, this is only a test.\n",
  :xfl :default}

 {:crc32 354754669,
  :flags
  {:ftext false,
   :fhcrc false,
   :fextra false,
   :fname false,
   :fcomment false},
  :isize 4,
  :os :unknown,
  :raw-fixed-header
  {:id1 31, :id2 139, :cm 8, :flg 0, :mtime 0, :xfl 0, :os 255},
  :uncompressed-string "jvm\n",
  :xfl :default}]
----
